packages:
    - 'packages/*'
    - 'apps/*'

autoInstallPeers: false

overrides:
    '@types/node': 24.13.3

allowBuilds:
    '@ast-grep/cli': true
    esbuild: true

onlyBuiltDependencies:
    - '@ast-grep/cli'
    - esbuild

verifyDepsBeforeRun: false
